#!/usr/bin/env python

from __future__ import print_function

from datetime import datetime

import signal
import subprocess
import sys
import time


LOGFILE = "/home/david/opt/dotfiles/meditation.log"
SOUND_EFFECT ="/home/david/dcs/audio/effects/bell.wav"


def ring_bell():
    subprocess.Popen(["aplay", SOUND_EFFECT, "-q"])


def log(start, end):
    with open(LOGFILE, "a") as f:
        f.write(start.strftime("From %y-%m-%d %H:%M:%S ") +
                end.strftime("till %y-%m-%d %H:%M:%S\n"))


def main(*args):
    if not args:
        args = (99999999,)

    signal.signal(signal.SIGINT, signal.default_int_handler)
    start_time = datetime.now()
    try:
        ring_bell()
        for duration in args:
            for m in xrange(duration, 0, -1):
                sys.stdout.write("Bell will sound again in {0} minutes\r".format(m))
                sys.stdout.flush()
                time.sleep(60)
            ring_bell()
    except KeyboardInterrupt:
        ring_bell()
    log(start_time, datetime.now())


if __name__ == "__main__":
    main(*[int(a) for a in sys.argv[1:]])
